data:
  alt: 'Oh Dear Application Health-overzicht met geslaagde controles voor de applicatie, cache, uitgaande e-mail en schijfruimte'
size: 143744
last_modified: 1785311729
width: 2230
height: 1212
mime_type: image/jpeg
duration: null
